//
// Generated file, do not edit! Created by opp_msgc 4.3 from NDNx/Messages/NdnApplPkt.msg.
//

#ifndef _NDNAPPLPKT_M_H_
#define _NDNAPPLPKT_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0403
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// cplusplus {{
#include "ApplPkt_m.h"
// }}



/**
 * Class generated from <tt>NDNx/Messages/NdnApplPkt.msg</tt> by opp_msgc.
 * <pre>
 * packet NdnApplPkt extends ApplPkt {
 *     
 *     	int maxNbHops;
 *     	int nbHops;
 *     	int msgId;
 *     	int isExtendedPkt;
 *         LAddress::L3Type creatorAddr;
 *         
 *         
 *         
 *         
 *         unsigned int selfPitBFM1;
 *         unsigned int selfPitBFM2;
 *         unsigned int selfPitBFM3;
 *         unsigned int selfPitBFM4;
 *         
 *         unsigned int selfCsBFM1;
 *         unsigned int selfCsBFM2;
 *         unsigned int selfCsBFM3;
 *         unsigned int selfCsBFM4;
 *         
 *         
 *         unsigned int ohPitBFM1;
 *         unsigned int ohPitBFM2;
 *         unsigned int ohPitBFM3;
 *         unsigned int ohPitBFM4;
 *         
 *         unsigned int ohCsBFM1;
 *         unsigned int ohCsBFM2;
 *         unsigned int ohCsBFM3;
 *         unsigned int ohCsBFM4;
 *         
 *         
 *         unsigned int thPitBFM1;
 *         unsigned int thPitBFM2;
 *         unsigned int thPitBFM3;
 *         unsigned int thPitBFM4;
 *         
 *         unsigned int thCsBFM1;
 *         unsigned int thCsBFM2;
 *         unsigned int thCsBFM3;
 *         unsigned int thCsBFM4;
 *         
 *         
 * }
 * </pre>
 */
class NdnApplPkt : public ::ApplPkt
{
  protected:
    int maxNbHops_var;
    int nbHops_var;
    int msgId_var;
    int isExtendedPkt_var;
    LAddress::L3Type creatorAddr_var;
    unsigned int selfPitBFM1_var;
    unsigned int selfPitBFM2_var;
    unsigned int selfPitBFM3_var;
    unsigned int selfPitBFM4_var;
    unsigned int selfCsBFM1_var;
    unsigned int selfCsBFM2_var;
    unsigned int selfCsBFM3_var;
    unsigned int selfCsBFM4_var;
    unsigned int ohPitBFM1_var;
    unsigned int ohPitBFM2_var;
    unsigned int ohPitBFM3_var;
    unsigned int ohPitBFM4_var;
    unsigned int ohCsBFM1_var;
    unsigned int ohCsBFM2_var;
    unsigned int ohCsBFM3_var;
    unsigned int ohCsBFM4_var;
    unsigned int thPitBFM1_var;
    unsigned int thPitBFM2_var;
    unsigned int thPitBFM3_var;
    unsigned int thPitBFM4_var;
    unsigned int thCsBFM1_var;
    unsigned int thCsBFM2_var;
    unsigned int thCsBFM3_var;
    unsigned int thCsBFM4_var;

  private:
    void copy(const NdnApplPkt& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const NdnApplPkt&);

  public:
    NdnApplPkt(const char *name=NULL, int kind=0);
    NdnApplPkt(const NdnApplPkt& other);
    virtual ~NdnApplPkt();
    NdnApplPkt& operator=(const NdnApplPkt& other);
    virtual NdnApplPkt *dup() const {return new NdnApplPkt(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getMaxNbHops() const;
    virtual void setMaxNbHops(int maxNbHops);
    virtual int getNbHops() const;
    virtual void setNbHops(int nbHops);
    virtual int getMsgId() const;
    virtual void setMsgId(int msgId);
    virtual int getIsExtendedPkt() const;
    virtual void setIsExtendedPkt(int isExtendedPkt);
    virtual LAddress::L3Type& getCreatorAddr();
    virtual const LAddress::L3Type& getCreatorAddr() const {return const_cast<NdnApplPkt*>(this)->getCreatorAddr();}
    virtual void setCreatorAddr(const LAddress::L3Type& creatorAddr);
    virtual unsigned int getSelfPitBFM1() const;
    virtual void setSelfPitBFM1(unsigned int selfPitBFM1);
    virtual unsigned int getSelfPitBFM2() const;
    virtual void setSelfPitBFM2(unsigned int selfPitBFM2);
    virtual unsigned int getSelfPitBFM3() const;
    virtual void setSelfPitBFM3(unsigned int selfPitBFM3);
    virtual unsigned int getSelfPitBFM4() const;
    virtual void setSelfPitBFM4(unsigned int selfPitBFM4);
    virtual unsigned int getSelfCsBFM1() const;
    virtual void setSelfCsBFM1(unsigned int selfCsBFM1);
    virtual unsigned int getSelfCsBFM2() const;
    virtual void setSelfCsBFM2(unsigned int selfCsBFM2);
    virtual unsigned int getSelfCsBFM3() const;
    virtual void setSelfCsBFM3(unsigned int selfCsBFM3);
    virtual unsigned int getSelfCsBFM4() const;
    virtual void setSelfCsBFM4(unsigned int selfCsBFM4);
    virtual unsigned int getOhPitBFM1() const;
    virtual void setOhPitBFM1(unsigned int ohPitBFM1);
    virtual unsigned int getOhPitBFM2() const;
    virtual void setOhPitBFM2(unsigned int ohPitBFM2);
    virtual unsigned int getOhPitBFM3() const;
    virtual void setOhPitBFM3(unsigned int ohPitBFM3);
    virtual unsigned int getOhPitBFM4() const;
    virtual void setOhPitBFM4(unsigned int ohPitBFM4);
    virtual unsigned int getOhCsBFM1() const;
    virtual void setOhCsBFM1(unsigned int ohCsBFM1);
    virtual unsigned int getOhCsBFM2() const;
    virtual void setOhCsBFM2(unsigned int ohCsBFM2);
    virtual unsigned int getOhCsBFM3() const;
    virtual void setOhCsBFM3(unsigned int ohCsBFM3);
    virtual unsigned int getOhCsBFM4() const;
    virtual void setOhCsBFM4(unsigned int ohCsBFM4);
    virtual unsigned int getThPitBFM1() const;
    virtual void setThPitBFM1(unsigned int thPitBFM1);
    virtual unsigned int getThPitBFM2() const;
    virtual void setThPitBFM2(unsigned int thPitBFM2);
    virtual unsigned int getThPitBFM3() const;
    virtual void setThPitBFM3(unsigned int thPitBFM3);
    virtual unsigned int getThPitBFM4() const;
    virtual void setThPitBFM4(unsigned int thPitBFM4);
    virtual unsigned int getThCsBFM1() const;
    virtual void setThCsBFM1(unsigned int thCsBFM1);
    virtual unsigned int getThCsBFM2() const;
    virtual void setThCsBFM2(unsigned int thCsBFM2);
    virtual unsigned int getThCsBFM3() const;
    virtual void setThCsBFM3(unsigned int thCsBFM3);
    virtual unsigned int getThCsBFM4() const;
    virtual void setThCsBFM4(unsigned int thCsBFM4);
};

inline void doPacking(cCommBuffer *b, NdnApplPkt& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, NdnApplPkt& obj) {obj.parsimUnpack(b);}


#endif // _NDNAPPLPKT_M_H_
